modules:
  - Body
  - Limb
  - Wheel
robot_types:
  TWSH:
    required_modules:
      Body: 1
      Limb: 4
      Wheel: 3
    performance: { speed: 2.3, throughput: 2.1 }
  QWDH:
    required_modules:
      Body: 1
      Limb: 6
      Wheel: 4
    performance: { speed: 2.7, throughput: 2.7 }
  Dragon:
    required_modules:
      Body: 0
      Limb: 2
      Wheel: 2
    performance: { speed: 1.8, throughput: 1.7 }
  Minimal:
    required_modules:
      Body: 0
      Limb: 1
      Wheel: 1
    performance: { speed: 1.0, throughput: 1.0 }
type_priority:
  TWSH: 1
  QWDH: 0
  Dragon: 2
  Minimal: 3