scenario_name: "toy_scenario"
output_dir: results

space:
  width: 100.0
  height: 100.0

sim:
  max_steps: 500
  interval_task_order: 100
  interval_robot_conf: 100
  reconstruct_duration: 10
  time_step: 1.0    # シミュレーションの時間ステップ

module_depot:
  position: [50.0, 50.0]

failure_model:
  module: morota.sim.failure_models
  class: WeibullFailureModel
  params:
    l: 200   # 故障率
    k: 1.5        # 形状パラメータ
    fatigue_move: {Body: 0.0, Limb: 0.5, Wheel: 1.0}
    fatigue_work: {Body: 0.0, Limb: 1.0, Wheel: 0.0}

configuration_planner:
  module: morota.sim.configuration_planner
  class: RandomConfigurationPlanner
  params:
    seed: 42
    num_workers: 10

task_allocator:
  module: morota.sim.task_allocator
  class: NearestIncompleteTaskSelector
  params: {}

# task_allocator:
#   module: morota.sim.task_selection
#   class: GABasedTaskSelector
#   params:
#     interval: 50
#     pop_size: 100
#     generations: 1000
#     elitism_rate: 0.1
#     L_max: 5
#     seed: 1234
#     trials: 5

modules: "datasets/modules_100_244.csv"
robot_setup: "datasets/robot_setup_norm.yml"
tasks:   "datasets/tasks_sobol.csv"