scenario_name: l400_gp250_ga250_p25_75_modules_100_244_hard_tasks_sobol
output_dir: results
space:
  width: 100.0
  height: 100.0
sim:
  max_steps: 500
  reconstruct_duration: 10
  time_step: 1.0
  H_limit: 500
module_depot:
  position:
  - 50.0
  - 50.0
failure_model:
  module: morota.sim.failure_models
  class: WeibullFailureModel
  params:
    l: 400
    k: 1.2
    fatigue_move:
      Body: 0.5
      Limb: 0.5
      Wheel: 1.0
    fatigue_work:
      Body: 0.5
      Limb: 1.0
      Wheel: 0.0
configuration_planner:
  module: morota.sim.configuration_planner
  class: GeneticPlanner
  params:
    interval: 250
    num_workers_max: 10
    pop_size: 20
    generations: 1000
    seed: 42
    trials: 1
    preference:
    - 0.25
    - 0.75
task_allocator:
  module: morota.sim.task_allocator
  class: GeneticAllocator
  params:
    interval: 250
    pop_size: 20
    generations: 500
    elitism_rate: 0.1
    L_max: 20
    seed: 1234
    trials: 1
modules: ../datasets/modules_100_244.csv
robot_setup: ../datasets/robot_setup_hard.yml
tasks: ../datasets/tasks_sobol.csv
