modules:
  - Body
  - Limb
  - Wheel
robot_types:
  TWSH:
    required_modules:
      Body: 1
      Limb: 4
      Wheel: 3
    performance: { speed: 2.0, throughput: 2.5 }
  QWDH:
    required_modules:
      Body: 1
      Limb: 6
      Wheel: 4
    performance: { speed: 3.0, throughput: 3.0 }
  Dragon:
    required_modules:
      Body: 0
      Limb: 2
      Wheel: 2
    performance: { speed: 1.5, throughput: 2.0 }
  Minimal:
    required_modules:
      Body: 0
      Limb: 1
      Wheel: 1
    performance: { speed: 1.0, throughput: 1.0 }
type_priority:
  TWSH: 1
  QWDH: 0
  Dragon: 2
  Minimal: 3