modules:
  - Body
  - Limb
  - Wheel
robot_types:
  TWSH:
    required_modules:
      Body: 1
      Limb: 4
      Wheel: 3
    performance: { speed: 3.2, throughput: 2.6 }
  QWDH:
    required_modules:
      Body: 1
      Limb: 6
      Wheel: 4
    performance: { speed: 4.3, throughput: 5.2 }
  Dragon:
    required_modules:
      Body: 0
      Limb: 2
      Wheel: 2
    performance: { speed: 2.2, throughput: 1.9 }
  Minimal:
    required_modules:
      Body: 0
      Limb: 1
      Wheel: 1
    performance: { speed: 1.0, throughput: 1.0 }
type_priority:
  TWSH: 1
  QWDH: 0
  Dragon: 2
  Minimal: 3